### ISSUE TITLE
Delete key no longer works

### ISSUE THREAD

**Issue by asampal** [metaeducation/ren-garden#10]
I'm pretty sure this used to work before the last few check-ins. Maybe it's the regression is related to the new copy/paste functionality.

On Windows 8.1, I get a "Attempt to Insert Non-Printables in Console" dialog when I try to use the Delete key in the input line.

**Comment by hostilefork** [comment]
I don't think the delete key ever worked; simply unimplemented.

Implemented here:

https://github.com/hostilefork/rencpp/commit/4448b8aeb291fa3dad5e529e700c642fc5d6980e
