### ISSUE TITLE
Switching to multi-line mode, deletes already entered text

### ISSUE THREAD

**Issue by asampal** [metaeducation/ren-garden#11]
On Windows 8.1, when I type something in the input and the hit Shift-Enter to switch to multi-line mode, the text that has been input so far is erased (replaced with "[ctrl-enter to evaluate]" and the insertion point is positioned on the next line.

I would expect that anything I've entered so far is retained, but just shifted down one line so that the first line can still contain the evaluation hint. An additional refinement would be to allow for the hint to not be displayed through a meta setting on the console. In that case, when switching to multi-line, the existing input would stay where it is, but hitting "Enter" would simply move the insertion point to the next line, as expected in this mode.

IMO, the positioning of the cursor relative to the line it is in should not change with a multi-line mode switch if it is anywhere else but the last position. If the insertion point is already at the end, switching to multi-line should place the insertion point on the line after the one with the originally inserted text (could be 1st or 2nd depending on the existence of the evaluation hint text).

**Comment by hostilefork** [comment]
>  If the insertion point is already at the end, switching to multi-line should place the insertion point on the line after the one with the originally inserted text

Good suggestion, implemented.

https://github.com/hostilefork/rencpp/commit/c92d7f4a56bfb00b94896955d3eea9a01fdf24e9

As for the deletion of already entered text...the changes in this commit took care of that...and it preserves not only your text but your selection state as well:

https://github.com/hostilefork/rencpp/commit/4d54e8998b32b2d7732c395da339a652c774fe56
