### ISSUE TITLE
Unexpected "what" returned

### ISSUE THREAD

**Issue by asampal** [metaeducation/ren-garden#12]
When the following line is entered:

```
console/meta [buffer ["onetwo" | 453]]
```

the console returns the word "what" as a result of the meta command invocation. The pending buffer is filled and insertion point positioned correctly, though. It seems to happen when "|" is specified, but not "||".

**Comment by hostilefork** [comment]
Stray debug code, resolved:

https://github.com/hostilefork/rencpp/commit/ffa72b02c9e1e4d1f262e12be64c68f2ba6bf3b3
