### ISSUE TITLE
Up/down arrows don't perform text navigation with multi-line, pasted text

### ISSUE THREAD

**Issue by asampal** [metaeducation/ren-garden#19]
After pasting text spanning multiple lines, the up/down arrows should navigate the pasted text rather than navigating through history, which is what currently happens.

**Comment by asampal** [comment]
https://github.com/hostilefork/rencpp/pull/67 submitted

**Comment by hostilefork** [comment]
Fix tested and works under Linux too.  Looks exactly right... great!
